const STORAGE_KEY='kyushoku-timer:prepare-records:v1';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let mode='prepare'; let prepare={running:false,startAt:0,elapsed:0}; let mogu={running:false,endAt:0,remaining:300}; let brush={running:false,endAt:0,remaining:180}; let tickId=null;
const fmt=n=>{n=Math.max(0,Math.floor(n));const m=Math.floor(n/60),s=n%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};
const fmtShort=n=>{n=Math.max(0,Math.round(n));return `${Math.floor(n/60)}分${String(n%60).padStart(2,'0')}秒`};
const records=()=>JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');
const saveRecords=r=>localStorage.setItem(STORAGE_KEY,JSON.stringify(r.slice(0,90)));
function updateClock(){const d=new Date();const time=d.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',hour12:false});$('#currentTime').textContent=time;$('#megaClock').textContent=time;$('#dateLine').textContent=d.toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'});}
function selectMode(next){if(next===mode)return;if(prepare.running||mogu.running||brush.running){showToast('動いているタイマーを先に止めよう。');return}mode=next;$$('.mode-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===next));$$('.mode-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===next));}
$$('.mode-tab').forEach(b=>b.addEventListener('click',()=>selectMode(b.dataset.mode)));
function setPrepareUI(){const sec=prepare.running?(Date.now()-prepare.startAt)/1000:prepare.elapsed;$('#prepareTimer').textContent=fmt(sec);$('#prepareStatus').textContent=prepare.running?'計測中':'待機中';$('#prepareStatusDot').classList.toggle('running',prepare.running);$('#prepareStart').disabled=prepare.running;$('#prepareFinish').disabled=!prepare.running;$('#prepareStart').textContent=prepare.running?'計測中…':'スタート';const pct=Math.min(sec/600*100,100);$('#prepareRing').style.setProperty('--ring',`${pct}%`);}
function startPrepare(){if(prepare.running)return;prepare.running=true;prepare.startAt=Date.now();prepare.elapsed=0;$('#prepareMessage').textContent='準備スタート！';$('#prepareSpeech').textContent='よーい、スタート！';setPrepareUI();}
function finishPrepare(){if(!prepare.running)return;prepare.elapsed=(Date.now()-prepare.startAt)/1000;prepare.running=false;const duration=Math.round(prepare.elapsed);const now=new Date();const end=now.toISOString();const start=new Date(now.getTime()-duration*1000);const r=records();r.unshift({date:end.slice(0,10),startTime:start.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}),endTime:now.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}),duration});saveRecords(r);$('#prepareMessage').textContent=`${fmtShort(duration)}！`;$('#prepareSpeech').textContent='できた！いただきます！';$('#prepareFinish').classList.add('celebrate');setTimeout(()=>$('#prepareFinish').classList.remove('celebrate'),600);setPrepareUI();showToast('準備時間を記録したよ。');}
function resetPrepare(){prepare={running:false,startAt:0,elapsed:0};$('#prepareMessage').textContent='準備をはじめよう！';$('#prepareSpeech').textContent='よーい、スタート！';setPrepareUI();}
$('#prepareStart').addEventListener('click',startPrepare);$('#prepareFinish').addEventListener('click',finishPrepare);$('#prepareReset').addEventListener('click',resetPrepare);
function renderApples(){const track=$('#appleTrack');track.innerHTML='';for(let i=0;i<10;i++){const span=document.createElement('span');span.className='apple';span.textContent='🍎';span.dataset.index=i;track.appendChild(span)}}
function updateMogu(){const rem=mogu.running?Math.max(0,(mogu.endAt-Date.now())/1000):mogu.remaining; mogu.remaining=rem;$('#moguTimer').textContent=`${Math.floor(rem/60)}:${String(Math.floor(rem%60)).padStart(2,'0')}`;const gone=Math.min(10,Math.floor((300-rem)/30));$$('.apple').forEach((a,i)=>a.classList.toggle('gone',i<gone));const msg=rem<=0?'ごちそうさまでした！':rem<=30?'もう少し！':rem<=150?'もぐもぐ、もぐもぐ。':'おいしく食べよう！';$('#moguNote').textContent=msg;$('#moguSpeech').textContent=msg;if(mogu.running&&rem<=0)finishMogu();}
function startMogu(){if(mogu.running)return;if(mogu.remaining<=0)mogu.remaining=300;mogu.running=true;mogu.endAt=Date.now()+mogu.remaining*1000;$('#moguStart').textContent='もぐもぐ中…';$('#moguStart').disabled=true;$('#moguSpeech').textContent='もぐもぐ、スタート！';updateMogu();}
function finishMogu(){mogu.running=false;mogu.remaining=0;$('#moguStart').disabled=false;$('#moguStart').textContent='もう一度スタート';renderApples();updateMogu();$('#moguNote').textContent='5分終了！ごちそうさまでした。';$('#moguSpeech').textContent='ごちそうさまでした！';showToast('もぐもぐタイム終了！');}
function resetMogu(){mogu={running:false,endAt:0,remaining:300};$('#moguStart').disabled=false;$('#moguStart').textContent='スタート';renderApples();updateMogu();}
$('#moguStart').addEventListener('click',startMogu);$('#moguReset').addEventListener('click',resetMogu);
function renderTeeth(){const t=$('#teethTrack');t.innerHTML='';for(let i=0;i<12;i++){const s=document.createElement('span');s.className='tooth';s.textContent='🦷';s.dataset.index=i;t.appendChild(s)}}
function updateBrush(){const rem=brush.running?Math.max(0,(brush.endAt-Date.now())/1000):brush.remaining;brush.remaining=rem;$('#brushTimer').textContent=`${Math.floor(rem/60)}:${String(Math.floor(rem%60)).padStart(2,'0')}`;const done=Math.min(12,Math.floor((180-rem)/15));$$('.tooth').forEach((t,i)=>t.classList.toggle('done',i<done));let guide=rem<=0?'3分みがけた！':rem<=60?'もう少し、ていねいに。':rem<=120?'上・下・奥を意識して。':'ゆっくり、ていねいにみがこう。';$('#brushGuide').textContent=guide;$('#brushSpeech').textContent=guide;if(brush.running&&rem<=0)finishBrush();}
function startBrush(){if(brush.running)return;if(brush.remaining<=0)brush.remaining=180;brush.running=true;brush.endAt=Date.now()+brush.remaining*1000;$('#brushStart').disabled=true;$('#brushStart').textContent='みがき中…';updateBrush();}
function finishBrush(){brush.running=false;brush.remaining=0;$('#brushStart').disabled=false;$('#brushStart').textContent='もう一度スタート';updateBrush();$('#brushGuide').textContent='3分みがけた！';$('#brushSpeech').textContent='ピカピカ！おつかれさま！';showToast('はみがきタイマー終了！');}
function resetBrush(){brush={running:false,endAt:0,remaining:180};$('#brushStart').disabled=false;$('#brushStart').textContent='スタート';renderTeeth();updateBrush();}
$('#brushStart').addEventListener('click',startBrush);$('#brushReset').addEventListener('click',resetBrush);
function openRecords(){const r=records();const now=new Date();const weekStart=new Date(now);const day=(now.getDay()+6)%7;weekStart.setDate(now.getDate()-day);weekStart.setHours(0,0,0,0);const weekly=r.filter(x=>new Date(`${x.date}T00:00:00`)>=weekStart);const avg=weekly.length?weekly.reduce((a,x)=>a+x.duration,0)/weekly.length:null;const best=r.length?Math.min(...r.map(x=>x.duration)):null;$('#avgStat').textContent=avg===null?'--':fmtShort(avg);$('#bestStat').textContent=best===null?'--':fmtShort(best);const list=$('#recordList');list.innerHTML=r.length?r.slice(0,14).map(x=>`<div class="record-item"><span>${x.date}<br>${x.startTime} → ${x.endTime}</span><strong>${fmtShort(x.duration)}</strong></div>`).join(''):'<div class="record-item"><span>まだ記録がありません。</span><strong>--</strong></div>';const chart=$('#recordChart');chart.innerHTML='';const recent=r.slice(0,7).reverse();const max=Math.max(600,...recent.map(x=>x.duration));recent.forEach(x=>{const w=document.createElement('div');w.className='bar-wrap';const b=document.createElement('div');b.className='bar';b.style.height=`${Math.max(5,x.duration/max*100)}%`;b.title=`${x.date} ${fmtShort(x.duration)}`;const l=document.createElement('div');l.className='bar-label';l.textContent=x.date.slice(5);w.append(b,l);chart.appendChild(w)});$('#recordModal').hidden=false;}
$('#openRecords').addEventListener('click',openRecords);$('#closeRecords').addEventListener('click',()=>$('#recordModal').hidden=true);$('#recordModal').addEventListener('click',e=>{if(e.target.id==='recordModal')e.currentTarget.hidden=true});$('#clearRecords').addEventListener('click',()=>{if(confirm('準備の記録をすべて削除しますか？')){localStorage.removeItem(STORAGE_KEY);openRecords();showToast('記録を削除したよ。')}});
let toastTimer;function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function loop(){if(prepare.running)setPrepareUI();if(mogu.running)updateMogu();if(brush.running)updateBrush();updateClock();}setInterval(loop,250);updateClock();renderApples();renderTeeth();updateMogu();updateBrush();setPrepareUI();
