const STORAGE_KEY='kyushoku-timer:prepare-records:v1';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let mode='home';
let prepare={running:false,paused:false,startAt:0,elapsed:0};
let mogu={running:false,paused:false,endAt:0,remaining:300};
let brush={running:false,paused:false,endAt:0,remaining:180};
const NAVIS=[
 {name:'なみ',url:'https://tt-sensei.github.io/navi-character-/assets/web/characters/nami/expressions/02-happy.webp'},
 {name:'さく',url:'https://tt-sensei.github.io/navi-character-/assets/web/characters/saku/expressions/02-happy.webp'},
 {name:'つき',url:'https://tt-sensei.github.io/navi-character-/assets/web/characters/tsuki/expressions/02-happy.webp'},
 {name:'かい',url:'https://tt-sensei.github.io/navi-character-/assets/web/characters/kai/expressions/02-happy.webp'},
 {name:'そら',url:'https://tt-sensei.github.io/navi-character-/assets/web/characters/sora/expressions/02-happy.webp'},
 {name:'りく',url:'https://tt-sensei.github.io/navi-character-/assets/web/characters/riku/expressions/02-happy.webp'}
];
let lastNavi=-1;
const fmt=n=>{n=Math.max(0,Math.floor(n));const m=Math.floor(n/60),s=n%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};
const fmtShort=n=>{n=Math.max(0,Math.round(n));return `${Math.floor(n/60)}分${String(n%60).padStart(2,'0')}秒`};
const records=()=>JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');const saveRecords=r=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(r.slice(0,90)));renderRecordPreview()};
function setAnalog(prefix,h,m,s){const p=prefix?`${prefix}Analog`:'analog';const a=$(`#${p}Hour`),b=$(`#${p}Minute`),c=$(`#${p}Second`);if(a)a.style.setProperty('--angle',`${h}deg`);if(b)b.style.setProperty('--angle',`${m}deg`);if(c)c.style.setProperty('--angle',`${s}deg`)}
function updateClock(){const d=new Date();const time=d.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',hour12:false});$('#currentTime').textContent=time;$('#megaClock').textContent=time;$('#dateLine').textContent=d.toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'});const sec=d.getSeconds()+d.getMilliseconds()/1000;const min=d.getMinutes()+sec/60;const hour=(d.getHours()%12)+min/60;const h=hour*30,m=min*6,s=sec*6;setAnalog('',h,m,s);setAnalog('mogu',h,m,s);setAnalog('clock',h,m,s);setAnalog('brush',h,m,s)}
function setNavi(message,forceNew=true){let i=Math.floor(Math.random()*NAVIS.length);if(forceNew&&NAVIS.length>1&&i===lastNavi)i=(i+1)%NAVIS.length;lastNavi=i;const n=NAVIS[i];const img=$('#floatingNaviImage');img.src=n.url;img.alt=`ナビキャラ ${n.name}`;$('#floatingSpeech').textContent=message;img.classList.remove('navi-pop');void img.offsetWidth;img.classList.add('navi-pop');}
const MODE_MESSAGES={prepare:'準備をはじめよう！',mogu:'おいしく食べよう！',clock:'今日もおいしく、楽しく。',brush:'きれいにみがこう！'};
function showTimerPage(next){mode=next;$('.top-page').style.display='none';$('.mode-stage').classList.add('is-open');$$('.mode-tab,.page-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===next));$$('.mode-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===next));setNavi(MODE_MESSAGES[next]);}
function goHome(){if(prepare.running||mogu.running||brush.running){showToast('動いているタイマーを先に止めよう。');return}mode='home';$('.mode-stage').classList.remove('is-open');$('.top-page').style.display='grid';$$('.mode-tab,.page-tab').forEach(b=>b.classList.remove('active'));setNavi('おいしく食べよう！');}
function selectMode(next){if(prepare.running||mogu.running||brush.running){showToast('動いているタイマーを先に止めよう。');return}showTimerPage(next);}
$$('.mode-tab,.page-tab').forEach(b=>b.addEventListener('click',()=>selectMode(b.dataset.mode)));
$('#homeButton').addEventListener('click',goHome);
function renderRecordPreview(){const list=$('#recordPreviewList');if(!list)return;const r=records().slice(0,3);if(!r.length){list.innerHTML='<div class="preview-empty">まだ記録がありません。<br>「じゅんび」で記録をつけよう！</div>';return}list.innerHTML=r.map((x,i)=>`<div class="preview-item"><span class="rank">${i+1}</span><span class="date">${x.date}</span><strong>${fmtShort(x.duration)}</strong></div>`).join('')}
function setPrepareUI(){const sec=prepare.running?(Date.now()-prepare.startAt)/1000:prepare.elapsed;$('#prepareTimer').textContent=fmt(sec);$('#prepareStatus').textContent=prepare.running?'計測中':prepare.paused?'一時停止中':'待機中';$('#prepareStatusDot').classList.toggle('running',prepare.running);$('#prepareStart').disabled=prepare.running;$('#prepareFinish').disabled=!prepare.running;$('#preparePause').disabled=!prepare.running&&!prepare.paused;$('#prepareStart').textContent=prepare.paused?'再開':'スタート';$('#preparePause').textContent='一時停止';const pct=Math.min(sec/600*100,100);$('#prepareRing').style.setProperty('--ring',`${pct}%`);}
function startPrepare(){if(prepare.running)return;const wasPaused=prepare.paused;if(wasPaused){prepare.running=true;prepare.startAt=Date.now()-prepare.elapsed*1000}else{prepare.running=true;prepare.paused=false;prepare.startAt=Date.now();prepare.elapsed=0}prepare.paused=false;setNavi(wasPaused?'準備を再開しよう！':'よーい、スタート！');setPrepareUI()}
function pausePrepare(){if(!prepare.running)return;prepare.elapsed=(Date.now()-prepare.startAt)/1000;prepare.running=false;prepare.paused=true;setPrepareUI();setNavi('ひとやすみ。時間を確認しよう！')}
function finishPrepare(){if(!prepare.running)return;prepare.elapsed=(Date.now()-prepare.startAt)/1000;prepare.running=false;prepare.paused=false;const duration=Math.round(prepare.elapsed);const now=new Date();const end=now.toISOString();const start=new Date(now.getTime()-duration*1000);const r=records();r.unshift({date:end.slice(0,10),startTime:start.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}),endTime:now.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}),duration});saveRecords(r);setNavi(`できた！${fmtShort(duration)}！`);$('#prepareFinish').classList.add('celebrate');setTimeout(()=>$('#prepareFinish').classList.remove('celebrate'),600);setPrepareUI();showToast('準備時間を記録したよ。')}
function resetPrepare(){prepare={running:false,paused:false,startAt:0,elapsed:0};setNavi('準備をはじめよう！');setPrepareUI()}
$('#prepareStart').addEventListener('click',startPrepare);$('#preparePause').addEventListener('click',pausePrepare);$('#prepareFinish').addEventListener('click',finishPrepare);$('#prepareReset').addEventListener('click',resetPrepare);
function renderApples(){const track=$('#appleTrack');track.innerHTML='';for(let i=0;i<10;i++){const span=document.createElement('span');span.className='apple';span.textContent='🍎';span.dataset.index=i;track.appendChild(span)}}
function updateMogu(){const rem=mogu.running?Math.max(0,(mogu.endAt-Date.now())/1000):mogu.remaining;mogu.remaining=rem;$('#moguTimer').textContent=`${Math.floor(rem/60)}:${String(Math.floor(rem%60)).padStart(2,'0')}`;const gone=Math.min(10,Math.floor((300-rem)/30));$$('.apple').forEach((a,i)=>a.classList.toggle('gone',i<gone));const msg=rem<=0?'ごちそうさまでした！':mogu.paused?'一時停止中。':rem<=30?'もう少し！':rem<=150?'もぐもぐ、もぐもぐ。':'おいしく食べよう！';$('#moguNote').textContent=msg;if(mogu.running&&rem<=0)finishMogu()}
function startMogu(){if(mogu.running)return;const wasPaused=mogu.paused;if(mogu.remaining<=0)mogu.remaining=300;mogu.running=true;mogu.paused=false;mogu.endAt=Date.now()+mogu.remaining*1000;$('#moguStart').textContent='もぐもぐ中…';$('#moguStart').disabled=true;$('#moguPause').disabled=false;setNavi(wasPaused?'もぐもぐを再開しよう！':'もぐもぐ、スタート！');updateMogu()}
function pauseMogu(){if(!mogu.running)return;mogu.remaining=Math.max(0,(mogu.endAt-Date.now())/1000);mogu.running=false;mogu.paused=true;$('#moguStart').disabled=false;$('#moguStart').textContent='再開';$('#moguPause').disabled=true;updateMogu();setNavi('ひとやすみ。ゆっくり食べよう！')}
function finishMogu(){mogu.running=false;mogu.paused=false;mogu.remaining=0;$('#moguStart').disabled=false;$('#moguStart').textContent='もう一度スタート';$('#moguPause').disabled=true;renderApples();updateMogu();$('#moguNote').textContent='5分終了！ごちそうさまでした。';setNavi('ごちそうさまでした！');showToast('もぐもぐタイム終了！')}
function resetMogu(){mogu={running:false,paused:false,endAt:0,remaining:300};$('#moguStart').disabled=false;$('#moguStart').textContent='スタート';$('#moguPause').disabled=true;renderApples();updateMogu();setNavi('おいしく食べよう！')}
$('#moguStart').addEventListener('click',startMogu);$('#moguPause').addEventListener('click',pauseMogu);$('#moguReset').addEventListener('click',resetMogu);
function renderTeeth(){const t=$('#teethTrack');t.innerHTML='';for(let i=0;i<12;i++){const s=document.createElement('span');s.className='tooth';s.textContent='🦷';s.dataset.index=i;t.appendChild(s)}}
function updateBrush(){const rem=brush.running?Math.max(0,(brush.endAt-Date.now())/1000):brush.remaining;brush.remaining=rem;$('#brushTimer').textContent=`${Math.floor(rem/60)}:${String(Math.floor(rem%60)).padStart(2,'0')}`;const done=Math.min(12,Math.floor((180-rem)/15));$$('.tooth').forEach((t,i)=>t.classList.toggle('done',i<done));let guide=rem<=0?'3分みがけた！':brush.paused?'一時停止中。':'もう少し、ていねいに。';if(rem>120&&!brush.paused)guide='ゆっくり、ていねいにみがこう。';else if(rem>60&&!brush.paused)guide='上・下・奥を意識して。';$('#brushGuide').textContent=guide;if(brush.running&&rem<=0)finishBrush()}
function startBrush(){if(brush.running)return;const wasPaused=brush.paused;if(brush.remaining<=0)brush.remaining=180;brush.running=true;brush.paused=false;brush.endAt=Date.now()+brush.remaining*1000;$('#brushStart').disabled=true;$('#brushStart').textContent='みがき中…';$('#brushPause').disabled=false;setNavi(wasPaused?'はみがきを再開しよう！':'きれいにみがこう！');updateBrush()}
function pauseBrush(){if(!brush.running)return;brush.remaining=Math.max(0,(brush.endAt-Date.now())/1000);brush.running=false;brush.paused=true;$('#brushStart').disabled=false;$('#brushStart').textContent='再開';$('#brushPause').disabled=true;updateBrush();setNavi('ひとやすみ。時間を確認しよう！')}
function finishBrush(){brush.running=false;brush.paused=false;brush.remaining=0;$('#brushStart').disabled=false;$('#brushStart').textContent='もう一度スタート';$('#brushPause').disabled=true;updateBrush();$('#brushGuide').textContent='3分みがけた！';setNavi('ピカピカ！おつかれさま！');showToast('はみがきタイマー終了！')}
function resetBrush(){brush={running:false,paused:false,endAt:0,remaining:180};$('#brushStart').disabled=false;$('#brushStart').textContent='スタート';$('#brushPause').disabled=true;renderTeeth();updateBrush();setNavi('きれいにみがこう！')}
$('#brushStart').addEventListener('click',startBrush);$('#brushPause').addEventListener('click',pauseBrush);$('#brushReset').addEventListener('click',resetBrush);
function deleteRecord(index){const r=records();if(index<0||index>=r.length)return;if(!confirm('この記録を削除しますか？'))return;r.splice(index,1);saveRecords(r);openRecords();showToast('記録を削除したよ。')}
function openRecords(){const r=records();const now=new Date();const weekStart=new Date(now);const day=(now.getDay()+6)%7;weekStart.setDate(now.getDate()-day);weekStart.setHours(0,0,0,0);const weekly=r.filter(x=>new Date(`${x.date}T00:00:00`)>=weekStart);const avg=weekly.length?weekly.reduce((a,x)=>a+x.duration,0)/weekly.length:null;const best=r.length?Math.min(...r.map(x=>x.duration)):null;$('#avgStat').textContent=avg===null?'--':fmtShort(avg);$('#bestStat').textContent=best===null?'--':fmtShort(best);const list=$('#recordList');list.innerHTML=r.length?r.slice(0,14).map((x,i)=>`<div class="record-item"><span>${x.date}<br>${x.startTime} → ${x.endTime}</span><strong>${fmtShort(x.duration)}</strong><button class="record-delete" data-record-index="${i}" type="button" aria-label="${x.date} ${fmtShort(x.duration)}の記録を削除">削除</button></div>`).join(''):'<div class="record-item"><span>まだ記録がありません。</span><strong>--</strong></div>';const chart=$('#recordChart');chart.innerHTML='';const recent=r.slice(0,7).reverse();const max=Math.max(600,...recent.map(x=>x.duration));recent.forEach(x=>{const w=document.createElement('div');w.className='bar-wrap';const b=document.createElement('div');b.className='bar';b.style.height=`${Math.max(5,x.duration/max*100)}%`;b.title=`${x.date} ${fmtShort(x.duration)}`;const l=document.createElement('div');l.className='bar-label';l.textContent=x.date.slice(5);w.append(b,l);chart.appendChild(w)});$('#recordModal').hidden=false}
$('#openRecords').addEventListener('click',openRecords);$('#closeRecords').addEventListener('click',()=>$('#recordModal').hidden=true);$('#recordModal').addEventListener('click',e=>{if(e.target.id==='recordModal')e.currentTarget.hidden=true});$('#recordList').addEventListener('click',e=>{const btn=e.target.closest('.record-delete');if(btn)deleteRecord(Number(btn.dataset.recordIndex))});$('#clearRecords').addEventListener('click',()=>{if(confirm('準備の記録をすべて削除しますか？')){localStorage.removeItem(STORAGE_KEY);renderRecordPreview();openRecords();showToast('記録を削除したよ。')}});
let toastTimer;function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function loop(){if(prepare.running)setPrepareUI();if(mogu.running)updateMogu();if(brush.running)updateBrush();updateClock()}setInterval(loop,250);updateClock();renderApples();renderTeeth();updateMogu();updateBrush();setPrepareUI();renderRecordPreview();setNavi('おいしく食べよう！',false);
